seed: 1234
tag: mlp_ensemble
log_dir: ./output

model_type: 'dino_vitb16,clip_vitb16,open_clip_vitb16'
feat_type: 'cls,embedding,embedding'
stride: '16,16,16'
hidden_size: 512

dataset_root: ./dataset/nights
num_workers: 16

lr: 0.0003
weight_decay: 0.0
batch_size: 512
epochs: 20
margin: 0.05