version: '3.8'

services:
  image_embeddings_qdrant:
    image: qdrant/qdrant:v1.12.5
    container_name: image_embeddings_qdrant
    # ports:
    #   - 6333:6333
    #   # - 6334:6334
    volumes:
      - ./notebooks:/notebooks
      - ./volumes/qdrant:/qdrant/storage
      - ./qdrant.yaml:/qdrant/config/production.yaml
    restart: always

  image_embeddings_jupyterlab:
    build:
      context: ./notebooks
      dockerfile: Dockerfile
    image: image_embeddings_jupyterlab
    container_name: image_embeddings_jupyterlab
    ipc: host
    ports:
      - 8654:8888
    volumes:
      - ./notebooks:/notebooks
    restart: always
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
