postfix: "feature_extractor"

seed: 42
precision: 16
accelerator: gpu
devices: 1
find_unused_parameters: False

dataset_root: /notebooks/downloads/birds-200-species/CUB_200_2011
logs_root: ./weights
dataframe_name: df.csv
logs_folder: birds_200_vitb14_dinov2

num_workers: 20
cache_size: 0

transforms_train:
  name: augs_hypvit_torch
  args:
    im_size: 224

transforms_val:
  name: norm_resize_hypvit_torch
  args:
    im_size: 224
    crop_size: 224

sampler:
  name: balance
  args:
    n_labels: 25
    n_instances: 6

bs_val: 64
max_epochs: 200
valid_period: 5

metric_args:
  metrics_to_exclude_from_visualization: [cmc,]
  cmc_top_k: [1, 5, 10]
  map_top_k: [1, 5, 10]
  fmr_vals: []
  pcf_variance: []
  return_only_overall_category: True
  visualize_only_overall_category: True

log_images: False

metric_for_checkpointing: OVERALL/cmc/1
mode_for_checkpointing: max

extractor:
  name: vit
  args:
    normalise_features: True
    use_multi_scale: False
    weights: vitb14_dinov2
    arch: vitb14

criterion:
  name: triplet_with_miner
  args:
    need_logs: True
    margin: 0.15
    reduction: mean
    miner:
      name: hard_triplets
      args: {}

optimizer:
  name: adamw
  args:
    lr: 1e-5


scheduling: null


# logger:
#   name: wandb  # requires <WANDB_API_KEY> as global env
#   args:
#     project: "test_project"


hydra_dir: ${logs_root}/${logs_folder}/

tags:
  - ${postfix}

hydra:
  run:
    dir: ${hydra_dir}
  searchpath:
   - pkg://oml.configs
  job:
    chdir: True